/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListDatadogIntegrations200ResponseEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDatadogIntegrations200ResponseEmbedded{}

// ListDatadogIntegrations200ResponseEmbedded struct for ListDatadogIntegrations200ResponseEmbedded
type ListDatadogIntegrations200ResponseEmbedded struct {
	Integrations []Integration `json:"integrations,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListDatadogIntegrations200ResponseEmbedded ListDatadogIntegrations200ResponseEmbedded

// NewListDatadogIntegrations200ResponseEmbedded instantiates a new ListDatadogIntegrations200ResponseEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDatadogIntegrations200ResponseEmbedded() *ListDatadogIntegrations200ResponseEmbedded {
	this := ListDatadogIntegrations200ResponseEmbedded{}
	return &this
}

// NewListDatadogIntegrations200ResponseEmbeddedWithDefaults instantiates a new ListDatadogIntegrations200ResponseEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDatadogIntegrations200ResponseEmbeddedWithDefaults() *ListDatadogIntegrations200ResponseEmbedded {
	this := ListDatadogIntegrations200ResponseEmbedded{}
	return &this
}

// GetIntegrations returns the Integrations field value if set, zero value otherwise.
func (o *ListDatadogIntegrations200ResponseEmbedded) GetIntegrations() []Integration {
	if o == nil || IsNil(o.Integrations) {
		var ret []Integration
		return ret
	}
	return o.Integrations
}

// GetIntegrationsOk returns a tuple with the Integrations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDatadogIntegrations200ResponseEmbedded) GetIntegrationsOk() ([]Integration, bool) {
	if o == nil || IsNil(o.Integrations) {
		return nil, false
	}
	return o.Integrations, true
}

// HasIntegrations returns a boolean if a field has been set.
func (o *ListDatadogIntegrations200ResponseEmbedded) HasIntegrations() bool {
	if o != nil && !IsNil(o.Integrations) {
		return true
	}

	return false
}

// SetIntegrations gets a reference to the given []Integration and assigns it to the Integrations field.
func (o *ListDatadogIntegrations200ResponseEmbedded) SetIntegrations(v []Integration) {
	o.Integrations = v
}

func (o ListDatadogIntegrations200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDatadogIntegrations200ResponseEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Integrations) {
		toSerialize["integrations"] = o.Integrations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListDatadogIntegrations200ResponseEmbedded) UnmarshalJSON(data []byte) (err error) {
	varListDatadogIntegrations200ResponseEmbedded := _ListDatadogIntegrations200ResponseEmbedded{}

	err = json.Unmarshal(data, &varListDatadogIntegrations200ResponseEmbedded)

	if err != nil {
		return err
	}

	*o = ListDatadogIntegrations200ResponseEmbedded(varListDatadogIntegrations200ResponseEmbedded)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "integrations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListDatadogIntegrations200ResponseEmbedded struct {
	value *ListDatadogIntegrations200ResponseEmbedded
	isSet bool
}

func (v NullableListDatadogIntegrations200ResponseEmbedded) Get() *ListDatadogIntegrations200ResponseEmbedded {
	return v.value
}

func (v *NullableListDatadogIntegrations200ResponseEmbedded) Set(val *ListDatadogIntegrations200ResponseEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullableListDatadogIntegrations200ResponseEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullableListDatadogIntegrations200ResponseEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDatadogIntegrations200ResponseEmbedded(val *ListDatadogIntegrations200ResponseEmbedded) *NullableListDatadogIntegrations200ResponseEmbedded {
	return &NullableListDatadogIntegrations200ResponseEmbedded{value: val, isSet: true}
}

func (v NullableListDatadogIntegrations200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDatadogIntegrations200ResponseEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


