/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListBackupRetentionPoliciesForAccount200ResponseEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListBackupRetentionPoliciesForAccount200ResponseEmbedded{}

// ListBackupRetentionPoliciesForAccount200ResponseEmbedded struct for ListBackupRetentionPoliciesForAccount200ResponseEmbedded
type ListBackupRetentionPoliciesForAccount200ResponseEmbedded struct {
	BackupRetentionPolicies []BackupRetentionPolicy `json:"backup_retention_policies,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListBackupRetentionPoliciesForAccount200ResponseEmbedded ListBackupRetentionPoliciesForAccount200ResponseEmbedded

// NewListBackupRetentionPoliciesForAccount200ResponseEmbedded instantiates a new ListBackupRetentionPoliciesForAccount200ResponseEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListBackupRetentionPoliciesForAccount200ResponseEmbedded() *ListBackupRetentionPoliciesForAccount200ResponseEmbedded {
	this := ListBackupRetentionPoliciesForAccount200ResponseEmbedded{}
	return &this
}

// NewListBackupRetentionPoliciesForAccount200ResponseEmbeddedWithDefaults instantiates a new ListBackupRetentionPoliciesForAccount200ResponseEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListBackupRetentionPoliciesForAccount200ResponseEmbeddedWithDefaults() *ListBackupRetentionPoliciesForAccount200ResponseEmbedded {
	this := ListBackupRetentionPoliciesForAccount200ResponseEmbedded{}
	return &this
}

// GetBackupRetentionPolicies returns the BackupRetentionPolicies field value if set, zero value otherwise.
func (o *ListBackupRetentionPoliciesForAccount200ResponseEmbedded) GetBackupRetentionPolicies() []BackupRetentionPolicy {
	if o == nil || IsNil(o.BackupRetentionPolicies) {
		var ret []BackupRetentionPolicy
		return ret
	}
	return o.BackupRetentionPolicies
}

// GetBackupRetentionPoliciesOk returns a tuple with the BackupRetentionPolicies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackupRetentionPoliciesForAccount200ResponseEmbedded) GetBackupRetentionPoliciesOk() ([]BackupRetentionPolicy, bool) {
	if o == nil || IsNil(o.BackupRetentionPolicies) {
		return nil, false
	}
	return o.BackupRetentionPolicies, true
}

// HasBackupRetentionPolicies returns a boolean if a field has been set.
func (o *ListBackupRetentionPoliciesForAccount200ResponseEmbedded) HasBackupRetentionPolicies() bool {
	if o != nil && !IsNil(o.BackupRetentionPolicies) {
		return true
	}

	return false
}

// SetBackupRetentionPolicies gets a reference to the given []BackupRetentionPolicy and assigns it to the BackupRetentionPolicies field.
func (o *ListBackupRetentionPoliciesForAccount200ResponseEmbedded) SetBackupRetentionPolicies(v []BackupRetentionPolicy) {
	o.BackupRetentionPolicies = v
}

func (o ListBackupRetentionPoliciesForAccount200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListBackupRetentionPoliciesForAccount200ResponseEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BackupRetentionPolicies) {
		toSerialize["backup_retention_policies"] = o.BackupRetentionPolicies
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListBackupRetentionPoliciesForAccount200ResponseEmbedded) UnmarshalJSON(data []byte) (err error) {
	varListBackupRetentionPoliciesForAccount200ResponseEmbedded := _ListBackupRetentionPoliciesForAccount200ResponseEmbedded{}

	err = json.Unmarshal(data, &varListBackupRetentionPoliciesForAccount200ResponseEmbedded)

	if err != nil {
		return err
	}

	*o = ListBackupRetentionPoliciesForAccount200ResponseEmbedded(varListBackupRetentionPoliciesForAccount200ResponseEmbedded)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "backup_retention_policies")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListBackupRetentionPoliciesForAccount200ResponseEmbedded struct {
	value *ListBackupRetentionPoliciesForAccount200ResponseEmbedded
	isSet bool
}

func (v NullableListBackupRetentionPoliciesForAccount200ResponseEmbedded) Get() *ListBackupRetentionPoliciesForAccount200ResponseEmbedded {
	return v.value
}

func (v *NullableListBackupRetentionPoliciesForAccount200ResponseEmbedded) Set(val *ListBackupRetentionPoliciesForAccount200ResponseEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullableListBackupRetentionPoliciesForAccount200ResponseEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullableListBackupRetentionPoliciesForAccount200ResponseEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBackupRetentionPoliciesForAccount200ResponseEmbedded(val *ListBackupRetentionPoliciesForAccount200ResponseEmbedded) *NullableListBackupRetentionPoliciesForAccount200ResponseEmbedded {
	return &NullableListBackupRetentionPoliciesForAccount200ResponseEmbedded{value: val, isSet: true}
}

func (v NullableListBackupRetentionPoliciesForAccount200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBackupRetentionPoliciesForAccount200ResponseEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


