/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
	"fmt"
)

// checks if the LlmIntegration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LlmIntegration{}

// LlmIntegration struct for LlmIntegration
type LlmIntegration struct {
	Id int32 `json:"id"`
	MetaType string `json:"_type"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	ProviderType string `json:"provider_type"`
	OrganizationId string `json:"organization_id"`
	ApiKey NullableString `json:"api_key"`
	BaseUrl NullableString `json:"base_url"`
	OpenaiOrganization NullableString `json:"openai_organization"`
	ApiVersion NullableString `json:"api_version"`
	AwsAccessKeyId NullableString `json:"aws_access_key_id"`
	AwsSecretAccessKey NullableString `json:"aws_secret_access_key"`
	AwsRegion NullableString `json:"aws_region"`
	Links *IntegrationLinks `json:"_links,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LlmIntegration LlmIntegration

// NewLlmIntegration instantiates a new LlmIntegration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLlmIntegration(id int32, metaType string, createdAt string, updatedAt string, providerType string, organizationId string, apiKey NullableString, baseUrl NullableString, openaiOrganization NullableString, apiVersion NullableString, awsAccessKeyId NullableString, awsSecretAccessKey NullableString, awsRegion NullableString) *LlmIntegration {
	this := LlmIntegration{}
	this.Id = id
	this.MetaType = metaType
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.ProviderType = providerType
	this.OrganizationId = organizationId
	this.ApiKey = apiKey
	this.BaseUrl = baseUrl
	this.OpenaiOrganization = openaiOrganization
	this.ApiVersion = apiVersion
	this.AwsAccessKeyId = awsAccessKeyId
	this.AwsSecretAccessKey = awsSecretAccessKey
	this.AwsRegion = awsRegion
	return &this
}

// NewLlmIntegrationWithDefaults instantiates a new LlmIntegration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLlmIntegrationWithDefaults() *LlmIntegration {
	this := LlmIntegration{}
	return &this
}

// GetId returns the Id field value
func (o *LlmIntegration) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LlmIntegration) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LlmIntegration) SetId(v int32) {
	o.Id = v
}

// GetMetaType returns the MetaType field value
func (o *LlmIntegration) GetMetaType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MetaType
}

// GetMetaTypeOk returns a tuple with the MetaType field value
// and a boolean to check if the value has been set.
func (o *LlmIntegration) GetMetaTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetaType, true
}

// SetMetaType sets field value
func (o *LlmIntegration) SetMetaType(v string) {
	o.MetaType = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *LlmIntegration) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *LlmIntegration) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *LlmIntegration) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *LlmIntegration) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *LlmIntegration) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *LlmIntegration) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetProviderType returns the ProviderType field value
func (o *LlmIntegration) GetProviderType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderType
}

// GetProviderTypeOk returns a tuple with the ProviderType field value
// and a boolean to check if the value has been set.
func (o *LlmIntegration) GetProviderTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderType, true
}

// SetProviderType sets field value
func (o *LlmIntegration) SetProviderType(v string) {
	o.ProviderType = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *LlmIntegration) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *LlmIntegration) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *LlmIntegration) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetApiKey returns the ApiKey field value
// If the value is explicit nil, the zero value for string will be returned
func (o *LlmIntegration) GetApiKey() string {
	if o == nil || o.ApiKey.Get() == nil {
		var ret string
		return ret
	}

	return *o.ApiKey.Get()
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LlmIntegration) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApiKey.Get(), o.ApiKey.IsSet()
}

// SetApiKey sets field value
func (o *LlmIntegration) SetApiKey(v string) {
	o.ApiKey.Set(&v)
}

// GetBaseUrl returns the BaseUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *LlmIntegration) GetBaseUrl() string {
	if o == nil || o.BaseUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.BaseUrl.Get()
}

// GetBaseUrlOk returns a tuple with the BaseUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LlmIntegration) GetBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseUrl.Get(), o.BaseUrl.IsSet()
}

// SetBaseUrl sets field value
func (o *LlmIntegration) SetBaseUrl(v string) {
	o.BaseUrl.Set(&v)
}

// GetOpenaiOrganization returns the OpenaiOrganization field value
// If the value is explicit nil, the zero value for string will be returned
func (o *LlmIntegration) GetOpenaiOrganization() string {
	if o == nil || o.OpenaiOrganization.Get() == nil {
		var ret string
		return ret
	}

	return *o.OpenaiOrganization.Get()
}

// GetOpenaiOrganizationOk returns a tuple with the OpenaiOrganization field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LlmIntegration) GetOpenaiOrganizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OpenaiOrganization.Get(), o.OpenaiOrganization.IsSet()
}

// SetOpenaiOrganization sets field value
func (o *LlmIntegration) SetOpenaiOrganization(v string) {
	o.OpenaiOrganization.Set(&v)
}

// GetApiVersion returns the ApiVersion field value
// If the value is explicit nil, the zero value for string will be returned
func (o *LlmIntegration) GetApiVersion() string {
	if o == nil || o.ApiVersion.Get() == nil {
		var ret string
		return ret
	}

	return *o.ApiVersion.Get()
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LlmIntegration) GetApiVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApiVersion.Get(), o.ApiVersion.IsSet()
}

// SetApiVersion sets field value
func (o *LlmIntegration) SetApiVersion(v string) {
	o.ApiVersion.Set(&v)
}

// GetAwsAccessKeyId returns the AwsAccessKeyId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *LlmIntegration) GetAwsAccessKeyId() string {
	if o == nil || o.AwsAccessKeyId.Get() == nil {
		var ret string
		return ret
	}

	return *o.AwsAccessKeyId.Get()
}

// GetAwsAccessKeyIdOk returns a tuple with the AwsAccessKeyId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LlmIntegration) GetAwsAccessKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AwsAccessKeyId.Get(), o.AwsAccessKeyId.IsSet()
}

// SetAwsAccessKeyId sets field value
func (o *LlmIntegration) SetAwsAccessKeyId(v string) {
	o.AwsAccessKeyId.Set(&v)
}

// GetAwsSecretAccessKey returns the AwsSecretAccessKey field value
// If the value is explicit nil, the zero value for string will be returned
func (o *LlmIntegration) GetAwsSecretAccessKey() string {
	if o == nil || o.AwsSecretAccessKey.Get() == nil {
		var ret string
		return ret
	}

	return *o.AwsSecretAccessKey.Get()
}

// GetAwsSecretAccessKeyOk returns a tuple with the AwsSecretAccessKey field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LlmIntegration) GetAwsSecretAccessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AwsSecretAccessKey.Get(), o.AwsSecretAccessKey.IsSet()
}

// SetAwsSecretAccessKey sets field value
func (o *LlmIntegration) SetAwsSecretAccessKey(v string) {
	o.AwsSecretAccessKey.Set(&v)
}

// GetAwsRegion returns the AwsRegion field value
// If the value is explicit nil, the zero value for string will be returned
func (o *LlmIntegration) GetAwsRegion() string {
	if o == nil || o.AwsRegion.Get() == nil {
		var ret string
		return ret
	}

	return *o.AwsRegion.Get()
}

// GetAwsRegionOk returns a tuple with the AwsRegion field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LlmIntegration) GetAwsRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AwsRegion.Get(), o.AwsRegion.IsSet()
}

// SetAwsRegion sets field value
func (o *LlmIntegration) SetAwsRegion(v string) {
	o.AwsRegion.Set(&v)
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *LlmIntegration) GetLinks() IntegrationLinks {
	if o == nil || IsNil(o.Links) {
		var ret IntegrationLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LlmIntegration) GetLinksOk() (*IntegrationLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *LlmIntegration) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given IntegrationLinks and assigns it to the Links field.
func (o *LlmIntegration) SetLinks(v IntegrationLinks) {
	o.Links = &v
}

func (o LlmIntegration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LlmIntegration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["_type"] = o.MetaType
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["provider_type"] = o.ProviderType
	toSerialize["organization_id"] = o.OrganizationId
	toSerialize["api_key"] = o.ApiKey.Get()
	toSerialize["base_url"] = o.BaseUrl.Get()
	toSerialize["openai_organization"] = o.OpenaiOrganization.Get()
	toSerialize["api_version"] = o.ApiVersion.Get()
	toSerialize["aws_access_key_id"] = o.AwsAccessKeyId.Get()
	toSerialize["aws_secret_access_key"] = o.AwsSecretAccessKey.Get()
	toSerialize["aws_region"] = o.AwsRegion.Get()
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LlmIntegration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"_type",
		"created_at",
		"updated_at",
		"provider_type",
		"organization_id",
		"api_key",
		"base_url",
		"openai_organization",
		"api_version",
		"aws_access_key_id",
		"aws_secret_access_key",
		"aws_region",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLlmIntegration := _LlmIntegration{}

	err = json.Unmarshal(data, &varLlmIntegration)

	if err != nil {
		return err
	}

	*o = LlmIntegration(varLlmIntegration)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "_type")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "provider_type")
		delete(additionalProperties, "organization_id")
		delete(additionalProperties, "api_key")
		delete(additionalProperties, "base_url")
		delete(additionalProperties, "openai_organization")
		delete(additionalProperties, "api_version")
		delete(additionalProperties, "aws_access_key_id")
		delete(additionalProperties, "aws_secret_access_key")
		delete(additionalProperties, "aws_region")
		delete(additionalProperties, "_links")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLlmIntegration struct {
	value *LlmIntegration
	isSet bool
}

func (v NullableLlmIntegration) Get() *LlmIntegration {
	return v.value
}

func (v *NullableLlmIntegration) Set(val *LlmIntegration) {
	v.value = val
	v.isSet = true
}

func (v NullableLlmIntegration) IsSet() bool {
	return v.isSet
}

func (v *NullableLlmIntegration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLlmIntegration(val *LlmIntegration) *NullableLlmIntegration {
	return &NullableLlmIntegration{value: val, isSet: true}
}

func (v NullableLlmIntegration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLlmIntegration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


