/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListAppsForAccount200ResponseEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAppsForAccount200ResponseEmbedded{}

// ListAppsForAccount200ResponseEmbedded struct for ListAppsForAccount200ResponseEmbedded
type ListAppsForAccount200ResponseEmbedded struct {
	Apps []App `json:"apps,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListAppsForAccount200ResponseEmbedded ListAppsForAccount200ResponseEmbedded

// NewListAppsForAccount200ResponseEmbedded instantiates a new ListAppsForAccount200ResponseEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAppsForAccount200ResponseEmbedded() *ListAppsForAccount200ResponseEmbedded {
	this := ListAppsForAccount200ResponseEmbedded{}
	return &this
}

// NewListAppsForAccount200ResponseEmbeddedWithDefaults instantiates a new ListAppsForAccount200ResponseEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAppsForAccount200ResponseEmbeddedWithDefaults() *ListAppsForAccount200ResponseEmbedded {
	this := ListAppsForAccount200ResponseEmbedded{}
	return &this
}

// GetApps returns the Apps field value if set, zero value otherwise.
func (o *ListAppsForAccount200ResponseEmbedded) GetApps() []App {
	if o == nil || IsNil(o.Apps) {
		var ret []App
		return ret
	}
	return o.Apps
}

// GetAppsOk returns a tuple with the Apps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAppsForAccount200ResponseEmbedded) GetAppsOk() ([]App, bool) {
	if o == nil || IsNil(o.Apps) {
		return nil, false
	}
	return o.Apps, true
}

// HasApps returns a boolean if a field has been set.
func (o *ListAppsForAccount200ResponseEmbedded) HasApps() bool {
	if o != nil && !IsNil(o.Apps) {
		return true
	}

	return false
}

// SetApps gets a reference to the given []App and assigns it to the Apps field.
func (o *ListAppsForAccount200ResponseEmbedded) SetApps(v []App) {
	o.Apps = v
}

func (o ListAppsForAccount200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAppsForAccount200ResponseEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Apps) {
		toSerialize["apps"] = o.Apps
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAppsForAccount200ResponseEmbedded) UnmarshalJSON(data []byte) (err error) {
	varListAppsForAccount200ResponseEmbedded := _ListAppsForAccount200ResponseEmbedded{}

	err = json.Unmarshal(data, &varListAppsForAccount200ResponseEmbedded)

	if err != nil {
		return err
	}

	*o = ListAppsForAccount200ResponseEmbedded(varListAppsForAccount200ResponseEmbedded)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "apps")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAppsForAccount200ResponseEmbedded struct {
	value *ListAppsForAccount200ResponseEmbedded
	isSet bool
}

func (v NullableListAppsForAccount200ResponseEmbedded) Get() *ListAppsForAccount200ResponseEmbedded {
	return v.value
}

func (v *NullableListAppsForAccount200ResponseEmbedded) Set(val *ListAppsForAccount200ResponseEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullableListAppsForAccount200ResponseEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullableListAppsForAccount200ResponseEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAppsForAccount200ResponseEmbedded(val *ListAppsForAccount200ResponseEmbedded) *NullableListAppsForAccount200ResponseEmbedded {
	return &NullableListAppsForAccount200ResponseEmbedded{value: val, isSet: true}
}

func (v NullableListAppsForAccount200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAppsForAccount200ResponseEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


