/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListWidgetsForDashboard200ResponseEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListWidgetsForDashboard200ResponseEmbedded{}

// ListWidgetsForDashboard200ResponseEmbedded struct for ListWidgetsForDashboard200ResponseEmbedded
type ListWidgetsForDashboard200ResponseEmbedded struct {
	Widgets []Widget `json:"widgets,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListWidgetsForDashboard200ResponseEmbedded ListWidgetsForDashboard200ResponseEmbedded

// NewListWidgetsForDashboard200ResponseEmbedded instantiates a new ListWidgetsForDashboard200ResponseEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListWidgetsForDashboard200ResponseEmbedded() *ListWidgetsForDashboard200ResponseEmbedded {
	this := ListWidgetsForDashboard200ResponseEmbedded{}
	return &this
}

// NewListWidgetsForDashboard200ResponseEmbeddedWithDefaults instantiates a new ListWidgetsForDashboard200ResponseEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListWidgetsForDashboard200ResponseEmbeddedWithDefaults() *ListWidgetsForDashboard200ResponseEmbedded {
	this := ListWidgetsForDashboard200ResponseEmbedded{}
	return &this
}

// GetWidgets returns the Widgets field value if set, zero value otherwise.
func (o *ListWidgetsForDashboard200ResponseEmbedded) GetWidgets() []Widget {
	if o == nil || IsNil(o.Widgets) {
		var ret []Widget
		return ret
	}
	return o.Widgets
}

// GetWidgetsOk returns a tuple with the Widgets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetsForDashboard200ResponseEmbedded) GetWidgetsOk() ([]Widget, bool) {
	if o == nil || IsNil(o.Widgets) {
		return nil, false
	}
	return o.Widgets, true
}

// HasWidgets returns a boolean if a field has been set.
func (o *ListWidgetsForDashboard200ResponseEmbedded) HasWidgets() bool {
	if o != nil && !IsNil(o.Widgets) {
		return true
	}

	return false
}

// SetWidgets gets a reference to the given []Widget and assigns it to the Widgets field.
func (o *ListWidgetsForDashboard200ResponseEmbedded) SetWidgets(v []Widget) {
	o.Widgets = v
}

func (o ListWidgetsForDashboard200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListWidgetsForDashboard200ResponseEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Widgets) {
		toSerialize["widgets"] = o.Widgets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListWidgetsForDashboard200ResponseEmbedded) UnmarshalJSON(data []byte) (err error) {
	varListWidgetsForDashboard200ResponseEmbedded := _ListWidgetsForDashboard200ResponseEmbedded{}

	err = json.Unmarshal(data, &varListWidgetsForDashboard200ResponseEmbedded)

	if err != nil {
		return err
	}

	*o = ListWidgetsForDashboard200ResponseEmbedded(varListWidgetsForDashboard200ResponseEmbedded)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "widgets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListWidgetsForDashboard200ResponseEmbedded struct {
	value *ListWidgetsForDashboard200ResponseEmbedded
	isSet bool
}

func (v NullableListWidgetsForDashboard200ResponseEmbedded) Get() *ListWidgetsForDashboard200ResponseEmbedded {
	return v.value
}

func (v *NullableListWidgetsForDashboard200ResponseEmbedded) Set(val *ListWidgetsForDashboard200ResponseEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullableListWidgetsForDashboard200ResponseEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullableListWidgetsForDashboard200ResponseEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListWidgetsForDashboard200ResponseEmbedded(val *ListWidgetsForDashboard200ResponseEmbedded) *NullableListWidgetsForDashboard200ResponseEmbedded {
	return &NullableListWidgetsForDashboard200ResponseEmbedded{value: val, isSet: true}
}

func (v NullableListWidgetsForDashboard200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListWidgetsForDashboard200ResponseEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


