/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ReleaseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReleaseLinks{}

// ReleaseLinks struct for ReleaseLinks
type ReleaseLinks struct {
	Service *ListAccountsForStack200ResponseLinksStack `json:"service,omitempty"`
	Containers *ListAccountsForStack200ResponseLinksStack `json:"containers,omitempty"`
	Self *ListAccountsForStack200ResponseLinksStack `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReleaseLinks ReleaseLinks

// NewReleaseLinks instantiates a new ReleaseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReleaseLinks() *ReleaseLinks {
	this := ReleaseLinks{}
	return &this
}

// NewReleaseLinksWithDefaults instantiates a new ReleaseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReleaseLinksWithDefaults() *ReleaseLinks {
	this := ReleaseLinks{}
	return &this
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *ReleaseLinks) GetService() ListAccountsForStack200ResponseLinksStack {
	if o == nil || IsNil(o.Service) {
		var ret ListAccountsForStack200ResponseLinksStack
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseLinks) GetServiceOk() (*ListAccountsForStack200ResponseLinksStack, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *ReleaseLinks) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given ListAccountsForStack200ResponseLinksStack and assigns it to the Service field.
func (o *ReleaseLinks) SetService(v ListAccountsForStack200ResponseLinksStack) {
	o.Service = &v
}

// GetContainers returns the Containers field value if set, zero value otherwise.
func (o *ReleaseLinks) GetContainers() ListAccountsForStack200ResponseLinksStack {
	if o == nil || IsNil(o.Containers) {
		var ret ListAccountsForStack200ResponseLinksStack
		return ret
	}
	return *o.Containers
}

// GetContainersOk returns a tuple with the Containers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseLinks) GetContainersOk() (*ListAccountsForStack200ResponseLinksStack, bool) {
	if o == nil || IsNil(o.Containers) {
		return nil, false
	}
	return o.Containers, true
}

// HasContainers returns a boolean if a field has been set.
func (o *ReleaseLinks) HasContainers() bool {
	if o != nil && !IsNil(o.Containers) {
		return true
	}

	return false
}

// SetContainers gets a reference to the given ListAccountsForStack200ResponseLinksStack and assigns it to the Containers field.
func (o *ReleaseLinks) SetContainers(v ListAccountsForStack200ResponseLinksStack) {
	o.Containers = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ReleaseLinks) GetSelf() ListAccountsForStack200ResponseLinksStack {
	if o == nil || IsNil(o.Self) {
		var ret ListAccountsForStack200ResponseLinksStack
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseLinks) GetSelfOk() (*ListAccountsForStack200ResponseLinksStack, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ReleaseLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ListAccountsForStack200ResponseLinksStack and assigns it to the Self field.
func (o *ReleaseLinks) SetSelf(v ListAccountsForStack200ResponseLinksStack) {
	o.Self = &v
}

func (o ReleaseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReleaseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.Containers) {
		toSerialize["containers"] = o.Containers
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReleaseLinks) UnmarshalJSON(data []byte) (err error) {
	varReleaseLinks := _ReleaseLinks{}

	err = json.Unmarshal(data, &varReleaseLinks)

	if err != nil {
		return err
	}

	*o = ReleaseLinks(varReleaseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "service")
		delete(additionalProperties, "containers")
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReleaseLinks struct {
	value *ReleaseLinks
	isSet bool
}

func (v NullableReleaseLinks) Get() *ReleaseLinks {
	return v.value
}

func (v *NullableReleaseLinks) Set(val *ReleaseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableReleaseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableReleaseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReleaseLinks(val *ReleaseLinks) *NullableReleaseLinks {
	return &NullableReleaseLinks{value: val, isSet: true}
}

func (v NullableReleaseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReleaseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


