/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListDisksForAccount200ResponseEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDisksForAccount200ResponseEmbedded{}

// ListDisksForAccount200ResponseEmbedded struct for ListDisksForAccount200ResponseEmbedded
type ListDisksForAccount200ResponseEmbedded struct {
	Disks []Disk `json:"disks,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListDisksForAccount200ResponseEmbedded ListDisksForAccount200ResponseEmbedded

// NewListDisksForAccount200ResponseEmbedded instantiates a new ListDisksForAccount200ResponseEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDisksForAccount200ResponseEmbedded() *ListDisksForAccount200ResponseEmbedded {
	this := ListDisksForAccount200ResponseEmbedded{}
	return &this
}

// NewListDisksForAccount200ResponseEmbeddedWithDefaults instantiates a new ListDisksForAccount200ResponseEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDisksForAccount200ResponseEmbeddedWithDefaults() *ListDisksForAccount200ResponseEmbedded {
	this := ListDisksForAccount200ResponseEmbedded{}
	return &this
}

// GetDisks returns the Disks field value if set, zero value otherwise.
func (o *ListDisksForAccount200ResponseEmbedded) GetDisks() []Disk {
	if o == nil || IsNil(o.Disks) {
		var ret []Disk
		return ret
	}
	return o.Disks
}

// GetDisksOk returns a tuple with the Disks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDisksForAccount200ResponseEmbedded) GetDisksOk() ([]Disk, bool) {
	if o == nil || IsNil(o.Disks) {
		return nil, false
	}
	return o.Disks, true
}

// HasDisks returns a boolean if a field has been set.
func (o *ListDisksForAccount200ResponseEmbedded) HasDisks() bool {
	if o != nil && !IsNil(o.Disks) {
		return true
	}

	return false
}

// SetDisks gets a reference to the given []Disk and assigns it to the Disks field.
func (o *ListDisksForAccount200ResponseEmbedded) SetDisks(v []Disk) {
	o.Disks = v
}

func (o ListDisksForAccount200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDisksForAccount200ResponseEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Disks) {
		toSerialize["disks"] = o.Disks
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListDisksForAccount200ResponseEmbedded) UnmarshalJSON(data []byte) (err error) {
	varListDisksForAccount200ResponseEmbedded := _ListDisksForAccount200ResponseEmbedded{}

	err = json.Unmarshal(data, &varListDisksForAccount200ResponseEmbedded)

	if err != nil {
		return err
	}

	*o = ListDisksForAccount200ResponseEmbedded(varListDisksForAccount200ResponseEmbedded)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "disks")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListDisksForAccount200ResponseEmbedded struct {
	value *ListDisksForAccount200ResponseEmbedded
	isSet bool
}

func (v NullableListDisksForAccount200ResponseEmbedded) Get() *ListDisksForAccount200ResponseEmbedded {
	return v.value
}

func (v *NullableListDisksForAccount200ResponseEmbedded) Set(val *ListDisksForAccount200ResponseEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullableListDisksForAccount200ResponseEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullableListDisksForAccount200ResponseEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDisksForAccount200ResponseEmbedded(val *ListDisksForAccount200ResponseEmbedded) *NullableListDisksForAccount200ResponseEmbedded {
	return &NullableListDisksForAccount200ResponseEmbedded{value: val, isSet: true}
}

func (v NullableListDisksForAccount200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDisksForAccount200ResponseEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


