/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the PlanLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanLinks{}

// PlanLinks struct for PlanLinks
type PlanLinks struct {
	Self *ListAccountsForStack200ResponseLinksStack `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PlanLinks PlanLinks

// NewPlanLinks instantiates a new PlanLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanLinks() *PlanLinks {
	this := PlanLinks{}
	return &this
}

// NewPlanLinksWithDefaults instantiates a new PlanLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanLinksWithDefaults() *PlanLinks {
	this := PlanLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *PlanLinks) GetSelf() ListAccountsForStack200ResponseLinksStack {
	if o == nil || IsNil(o.Self) {
		var ret ListAccountsForStack200ResponseLinksStack
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanLinks) GetSelfOk() (*ListAccountsForStack200ResponseLinksStack, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *PlanLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ListAccountsForStack200ResponseLinksStack and assigns it to the Self field.
func (o *PlanLinks) SetSelf(v ListAccountsForStack200ResponseLinksStack) {
	o.Self = &v
}

func (o PlanLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PlanLinks) UnmarshalJSON(data []byte) (err error) {
	varPlanLinks := _PlanLinks{}

	err = json.Unmarshal(data, &varPlanLinks)

	if err != nil {
		return err
	}

	*o = PlanLinks(varPlanLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePlanLinks struct {
	value *PlanLinks
	isSet bool
}

func (v NullablePlanLinks) Get() *PlanLinks {
	return v.value
}

func (v *NullablePlanLinks) Set(val *PlanLinks) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanLinks) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanLinks(val *PlanLinks) *NullablePlanLinks {
	return &NullablePlanLinks{value: val, isSet: true}
}

func (v NullablePlanLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


