/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListContainersForRelease200ResponseEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListContainersForRelease200ResponseEmbedded{}

// ListContainersForRelease200ResponseEmbedded struct for ListContainersForRelease200ResponseEmbedded
type ListContainersForRelease200ResponseEmbedded struct {
	Containers []Container `json:"containers,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListContainersForRelease200ResponseEmbedded ListContainersForRelease200ResponseEmbedded

// NewListContainersForRelease200ResponseEmbedded instantiates a new ListContainersForRelease200ResponseEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListContainersForRelease200ResponseEmbedded() *ListContainersForRelease200ResponseEmbedded {
	this := ListContainersForRelease200ResponseEmbedded{}
	return &this
}

// NewListContainersForRelease200ResponseEmbeddedWithDefaults instantiates a new ListContainersForRelease200ResponseEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListContainersForRelease200ResponseEmbeddedWithDefaults() *ListContainersForRelease200ResponseEmbedded {
	this := ListContainersForRelease200ResponseEmbedded{}
	return &this
}

// GetContainers returns the Containers field value if set, zero value otherwise.
func (o *ListContainersForRelease200ResponseEmbedded) GetContainers() []Container {
	if o == nil || IsNil(o.Containers) {
		var ret []Container
		return ret
	}
	return o.Containers
}

// GetContainersOk returns a tuple with the Containers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListContainersForRelease200ResponseEmbedded) GetContainersOk() ([]Container, bool) {
	if o == nil || IsNil(o.Containers) {
		return nil, false
	}
	return o.Containers, true
}

// HasContainers returns a boolean if a field has been set.
func (o *ListContainersForRelease200ResponseEmbedded) HasContainers() bool {
	if o != nil && !IsNil(o.Containers) {
		return true
	}

	return false
}

// SetContainers gets a reference to the given []Container and assigns it to the Containers field.
func (o *ListContainersForRelease200ResponseEmbedded) SetContainers(v []Container) {
	o.Containers = v
}

func (o ListContainersForRelease200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListContainersForRelease200ResponseEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Containers) {
		toSerialize["containers"] = o.Containers
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListContainersForRelease200ResponseEmbedded) UnmarshalJSON(data []byte) (err error) {
	varListContainersForRelease200ResponseEmbedded := _ListContainersForRelease200ResponseEmbedded{}

	err = json.Unmarshal(data, &varListContainersForRelease200ResponseEmbedded)

	if err != nil {
		return err
	}

	*o = ListContainersForRelease200ResponseEmbedded(varListContainersForRelease200ResponseEmbedded)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "containers")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListContainersForRelease200ResponseEmbedded struct {
	value *ListContainersForRelease200ResponseEmbedded
	isSet bool
}

func (v NullableListContainersForRelease200ResponseEmbedded) Get() *ListContainersForRelease200ResponseEmbedded {
	return v.value
}

func (v *NullableListContainersForRelease200ResponseEmbedded) Set(val *ListContainersForRelease200ResponseEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullableListContainersForRelease200ResponseEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullableListContainersForRelease200ResponseEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListContainersForRelease200ResponseEmbedded(val *ListContainersForRelease200ResponseEmbedded) *NullableListContainersForRelease200ResponseEmbedded {
	return &NullableListContainersForRelease200ResponseEmbedded{value: val, isSet: true}
}

func (v NullableListContainersForRelease200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListContainersForRelease200ResponseEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


