/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListDashboards200ResponseEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDashboards200ResponseEmbedded{}

// ListDashboards200ResponseEmbedded struct for ListDashboards200ResponseEmbedded
type ListDashboards200ResponseEmbedded struct {
	Dashboards []Dashboard `json:"dashboards,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListDashboards200ResponseEmbedded ListDashboards200ResponseEmbedded

// NewListDashboards200ResponseEmbedded instantiates a new ListDashboards200ResponseEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDashboards200ResponseEmbedded() *ListDashboards200ResponseEmbedded {
	this := ListDashboards200ResponseEmbedded{}
	return &this
}

// NewListDashboards200ResponseEmbeddedWithDefaults instantiates a new ListDashboards200ResponseEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDashboards200ResponseEmbeddedWithDefaults() *ListDashboards200ResponseEmbedded {
	this := ListDashboards200ResponseEmbedded{}
	return &this
}

// GetDashboards returns the Dashboards field value if set, zero value otherwise.
func (o *ListDashboards200ResponseEmbedded) GetDashboards() []Dashboard {
	if o == nil || IsNil(o.Dashboards) {
		var ret []Dashboard
		return ret
	}
	return o.Dashboards
}

// GetDashboardsOk returns a tuple with the Dashboards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDashboards200ResponseEmbedded) GetDashboardsOk() ([]Dashboard, bool) {
	if o == nil || IsNil(o.Dashboards) {
		return nil, false
	}
	return o.Dashboards, true
}

// HasDashboards returns a boolean if a field has been set.
func (o *ListDashboards200ResponseEmbedded) HasDashboards() bool {
	if o != nil && !IsNil(o.Dashboards) {
		return true
	}

	return false
}

// SetDashboards gets a reference to the given []Dashboard and assigns it to the Dashboards field.
func (o *ListDashboards200ResponseEmbedded) SetDashboards(v []Dashboard) {
	o.Dashboards = v
}

func (o ListDashboards200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDashboards200ResponseEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dashboards) {
		toSerialize["dashboards"] = o.Dashboards
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListDashboards200ResponseEmbedded) UnmarshalJSON(data []byte) (err error) {
	varListDashboards200ResponseEmbedded := _ListDashboards200ResponseEmbedded{}

	err = json.Unmarshal(data, &varListDashboards200ResponseEmbedded)

	if err != nil {
		return err
	}

	*o = ListDashboards200ResponseEmbedded(varListDashboards200ResponseEmbedded)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "dashboards")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListDashboards200ResponseEmbedded struct {
	value *ListDashboards200ResponseEmbedded
	isSet bool
}

func (v NullableListDashboards200ResponseEmbedded) Get() *ListDashboards200ResponseEmbedded {
	return v.value
}

func (v *NullableListDashboards200ResponseEmbedded) Set(val *ListDashboards200ResponseEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullableListDashboards200ResponseEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullableListDashboards200ResponseEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDashboards200ResponseEmbedded(val *ListDashboards200ResponseEmbedded) *NullableListDashboards200ResponseEmbedded {
	return &NullableListDashboards200ResponseEmbedded{value: val, isSet: true}
}

func (v NullableListDashboards200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDashboards200ResponseEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


